import { Injectable } from '@angular/core';
import { Router } from '@angular/router';
import { jwtDecode } from 'jwt-decode';

// import {sign} from 'jsonwebtoken';

@Injectable({
  providedIn: 'root',
})
export class Auth {
  private _loggedIn = false;


  constructor(private router: Router) {
    this._loggedIn = this.isLoggedIn();
  }


  public authenticateUser(): void {
    // generate JWT token
    let login_token = this.generateToken(); // could be generated by backend
    this.setToken(login_token);
    this._loggedIn = true;
  }

  public loggedIn(): boolean {
    return this._loggedIn;
  }

  public setToken(token: string): void {
    localStorage.setItem('JWT_token', token);
  }

  getToken(): string | null {
    return localStorage.getItem('JWT_token');
  }

  logout(): void {
    localStorage.removeItem('JWT_token');
    this.router.navigate(['/']);
    this._loggedIn = false; 
  }

  isLoggedIn(): boolean {
    const token = this.getToken();
    console.log(token);
    if (!token) return false;

    try {

      const decoded: any = jwtDecode(token); // TODO: check return/return type
      console.log(Date.now());
      console.log(decoded);
      return decoded.exp * 1000 > Date.now();
    } catch {
      return false;
    }
  }

  generateToken(): string {


    const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IlN1cnlhIFNvbGFpYXBwYW4iLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNzY0NDgxNzAwLCJleHAiOjE3NjQ1NjgxMDB9.MouMrBmwDCNQxey2IulSipuhYm3STMix5bafeOKBPVs"

    return token;
  }

}